[Icon Theme]
Name=SnokOS Light
Name[ar]=نسيم فاتح
Name[ca@valencia]=SnokOS clara
Name[en_GB]=SnokOS Light
Name[eu]=SnokOS argia
Name[fr]=SnokOS clair
Name[x-test]=xxSnokOS Lightxx
Name[zh_CN]=SnokOS 微风浅色
Name[zh_TW]=SnokOS Light
Comment=SnokOS Light by the KDE VDG
Comment[ar]=SnokOS فاتح من مجموعة تصميم SnokOS
Comment[en_GB]=SnokOS Light by the SnokOS
Comment[fr]=Brise Light par SnokOS
Comment[x-test]=xxSnokOS Light by the SnokOS
